apiVersion: 1

datasources:
  - name: Tempo (Wall)
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    jsonData:
      httpMethod: GET
      tracesToProfiles:
        datasourceUid: pyroscope
        profileTypeId: "wall:wall:nanoseconds:wall:nanoseconds"
        customQuery: true
        query: '{service_name="demo-app-wall"}'
        tags:
          - key: service.name
            value: service_name

  - name: Pyroscope (Wall)
    type: grafana-pyroscope-datasource
    uid: pyroscope
    access: proxy
    url: http://pyroscope:4040
    jsonData:
      profileTypeId: "wall:wall:nanoseconds:wall:nanoseconds"

  - name: Tempo (CPU)
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      tracesToProfiles:
        datasourceUid: pyroscope-cpu
        profileTypeId: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
        customQuery: true
        query: '{service_name="demo-app-cpu"}'
        tags:
          - key: service.name
            value: service_name

  - name: Pyroscope (CPU)
    type: grafana-pyroscope-datasource
    uid: pyroscope-cpu
    access: proxy
    url: http://pyroscope:4040
    jsonData:
      profileTypeId: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
